### PR TITLE
Fixes to visual c++ for #492

### PR DESCRIPTION
**Pull request by Andne**
Some changes were made for MinGW, also marked those changes to apply to Visual C++

### CODE REVIEW

**Comment by arstrube** [comment]
@Andne thanks again, Andy.

I was thinking of doing this myself, but don't currently have access to Visual Studio. Actually, there are two more function pointer interfaces that need adding to Visual C++ as well... sorry about that.

**Comment by Andne** [comment]
@arstrube  No problem.

I noticed some linker errors until I fixed made the changes to UtestPlatformTest.cpp, they involved a fork and a wait platform-specific function.  I left them out since once I disabled the fork tests there weren't any errors, so I figured that they could be left until someone figures out how to make them work in the first place.

Also, I added a commit to add several missing files to AllTest.vcxproj.  My code tree has a different project file structure, so I didn't notice them at first.

**Comment by arstrube** [comment]
You are right -- these functions are new and actually not needed for Visual C++

**Comment by arstrube** [comment]
Vow, some of these other files have been missing in the project for a long time.

**Pull request merged**
