### PR TITLE
Fix UtestPlatform.cpp plus tests for IAR

### PR DESCRIPTION
**Pull request by arstrube**
@imr I hope the #define for IAR (`__IAR_SYSTEMS_ICC__`) hits the mark.

Please, let us know when this compiles and tests correctly on your system!

### CODE REVIEW

**Comment by arstrube** [comment]
@basvodde - should we supply empty dummy implementations for the Mutex stuff (as in this PR), or would it be better to have it bark loudly (as before), so new users __know__ the Mutex stuff is not implemented? 

@imr Would a 'real' implementation of some sort for the Cortex M3 be helpful?

**Comment by imr** [comment]
@arstrube It might be helpful, but is not necessary now. I think one approach might be through CMSIS, which would cover the entire Cortex M line.

**Comment by basvodde** [comment]
@arstrube Either way. I usually prefer FAILing, but either way is ok.

**Comment by arstrube** [comment]
@basvodde me, too. But it's merged already ;-). I meant to roll it back to the previous commit if we agreed on FAIL(). The one ugly thing about FAIL is that it occurs in main(), so maybe doing nothing is actually best.....

**Comment by basvodde** [comment]
If you feel a need to add the FAIL, please do. I'll merge it as I have no really strong opinion on this one.

**Pull request merged**
