### PR TITLE
Restore coveralls integration

### PR DESCRIPTION
**Pull request by thetic**

### CODE REVIEW

**Comment by thetic** [comment]
https://coveralls.io/builds/50742011

**Comment by thetic** [comment]
This stopped running in November: https://coveralls.io/github/cpputest/cpputest?branch=master

**Comment by basvodde** [comment]
Thanks. Gradually merging the open pull requests

**Comment by basvodde** [comment]
Oh, this one cannot be merged at the moment, there is a conflict with another change

**Pull request merged**
