### PR TITLE
Fix SimpleString Tests for 16bit per byte systems (cl2000)

### PR DESCRIPTION
**Pull request by arstrube**
Forgot to fix these tests -- some of them were still failing on the cl2000.

### CODE REVIEW

**Comment by basvodde** [comment]
Coverage decreased by adding a test!

**Comment by arstrube** [comment]
Yeah, but it decreased by 0,0% :-P

**Comment by basvodde** [comment]
So what should I do?

**Comment by arstrube** [comment]
You could merge it. Or I could "fix" it :-). There are 92 hits less, in some 11.000, decreasing coverage from 100% to 100%.

**Comment by arstrube** [comment]
Actually, I have no idea how to fix it. The #if - #else'd test (the part that's compiled) is the same as before. The other tests are just doing a calculation differently, which ends up with the same value as before on this platform.

**Comment by arstrube** [comment]
I take this to mean that I can point the coverage badge at cpputest.github.io to cpplutest/cpputest now ;-).

**Comment by arstrube** [comment]
A person not providing tests will get a red flag from now on, it seems.....

**Comment by arstrube** [comment]
@basvodde 

1. How did you include the Coveralls check in the build? I see no commit. But I also don't see how to configure this from Github or Coveralls. The check is not active on my fork.

2. Is there a way to configure the Coveralls check? I think even the smallest change in percentages is significant. However, I don't think decreased line counts need to be taken into account. In the extreme, decreased line count could mean more efficient code... What makes it worse is that Coveralls doesn't give any indication in the code (at least I couldn't find any) that tells us exactly which lines were executed fewer times, and it would be potentially bothersome to fix this by means of guesswork.

**Comment by basvodde** [comment]
1) No idea, I just did what you told me last time :)

2) No idea either :)

Previously the @coveralls github account answered you, perhaps it can do that again :P

**Comment by arstrube** [comment]
There seems to be an open issue against Coveralls regarding 2). So I think it will be addressed in due time :-)

As for 1), it turned out to be surprisingly simple. It's a new feature, and you got it, because you linked to Coveralls fairly recently. After I removed Coveralls from my fork and added it again, I am now getting the same feedback. Only on pull requests though, so in order to see it, I must create a PR against my own fork.

**Comment by basvodde** [comment]
So, nothing I should do?

**Comment by arstrube** [comment]
I guess not. Except accepting the occasional PR that 'decreases' coverage by 0.00000% ;-)

**Pull request merged**
