### PR TITLE
 More interfaces for MockSupport_c...

### PR DESCRIPTION
**Pull request by arstrube**
This fixes issue #840.

### CODE REVIEW

**Comment by arstrube** [comment]
I guess this PR is growing way too large.....

**Comment by cuitoldfish** [comment]
seems Travis CI is broken?

**Comment by arstrube** [comment]
@cuitoldfish - Yup. Travis isn't well at all. Sort of on-and-off erroring all the time....

**Comment by arstrube** [comment]
That's about it. There's a small bit of 'residue', which either doesn't make sense in C or I'm still unsure about (stuff within /** */ in MockSupport_c.h). Maybe @basvodde could have a look at those.

**Comment by basvodde** [comment]
Can you remove the comments ?

**Comment by arstrube** [comment]
Sure, but only after discussming them with you :-). I'd like your opinion on which ones might end up as interface, and which ones as simply being removed.

There are also some whitespace changes in two unrelated files that krept in. I can split those off for another PR if you prefer.

**Comment by basvodde** [comment]
I suggest to not implement them if we don't need them :)

Would be better if whitespace changes are in other PRs in the future, but lets not add more work now?

**Comment by arstrube** [comment]
Line coverage for this PR should be 100%.

**Pull request merged**
