### PR TITLE
Remove redundant Platforms/Xxx/Platform.h

### PR DESCRIPTION
**Pull request by arstrube**
Was: Add Dos/Platforms.h.

### CODE REVIEW

**Comment by basvodde** [comment]
Do we need a Platform.h?

**Comment by arstrube** [comment]
No, not at this point. But it seems all platforms have one, whethere they need it or not?

**Comment by basvodde** [comment]
So far, we've attempted to avoid depending from platform independent code to platform dependent code (in #include). So, guess the others can safely be removed?

**Comment by arstrube** [comment]
Yes. The only one that's actually used is the C2000 one.

**Comment by arstrube** [comment]
We only need stdint.h `c2000/stdint.h`.

**Comment by arstrube** [comment]
Had to remove the hidden tentacles in Visual Studio 201x projects.

Let's say we are actively discouraging the use of `Platform.h` henceforth :-)

**Comment by arstrube** [comment]
@basvodde anything wrong with this?

**Comment by basvodde** [comment]
No, was just focusing on MockSupport :)

**Pull request merged**
