### PR TITLE
fix #884 Option2 for append scope name

### LINKED ISSUE #884: Output mock scope at failure
If a scoped mock is used, it' would be helpful to print out it's scope on failure.

## Problem

1. If mocks have the same name - but different scopes, it's hard to say which one is actually meant
1. If there's a typo in the scopes name, it's difficult to trace back the failure

## Examples

Assuming following test:
```cpp
void fn(int i)
{
    mock().actualCall("fn").withParameter("i", i);
}

void fnScope(int i)
{
    mock("scope").actualCall("fn").withParameter("i", i);
}


TEST_GROUP(ScopeTest)
{
    void teardown() override
    {
        mock().checkExpectations();
        mock().clear();
    }
};
```

### Example 1: Same name but different scopes

Both mocks have the same name, but different scopes:

```cpp
TEST(ScopeTest, noScope)
{
    mock().expectOneCall("fn").withParameter("i", 3);
    fn(4);
}

TEST(ScopeTest, withScope)
{
    mock("scope").expectOneCall("fn").withParameter("i", 3);
    fnScope(4);
}
```

***Output (shortened):***

The actual message is twice exactly the same.

```
test/ScopeTest.cpp:31: error: Failure in TEST(ScopeTest, withScope)
	Mock Failure: Unexpected parameter value to parameter "i" to function "fn": <4>
	EXPECTED calls that DID NOT happen related to function: fn
		fn -> int i: <3>
	ACTUAL calls that DID happen related to function: fn
		<none>
	ACTUAL unexpected parameter passed to function: fn
		int i: <4>

test/ScopeTest.cpp:25: error: Failure in TEST(ScopeTest, noScope)
	Mock Failure: Unexpected parameter value to parameter "i" to function "fn": <4>
	EXPECTED calls that DID NOT happen related to function: fn
		fn -> int i: <3>
	ACTUAL calls that DID happen related to function: fn
		<none>
	ACTUAL unexpected parameter passed to function: fn
		int i: <4>
```

### Example 2: Typo in scope name

There's a typo in the scope name:

```cpp
TEST(ScopeTest, typoScope)
{
    mock("Scope").expectOneCall("fn").withParameter("i", 3);
    /*    ^-- typo */
    fnScope(4);
}
```

***Output (shortened):***

It's difficult to say, what *really* caused the test to fail, since the function is called as expected.
```
test/ScopeTest.cpp:37: error: Failure in TEST(ScopeTest, typoScope)
	Mock Failure: Unexpected call to function: fn
	EXPECTED calls that did NOT happen:
		<none>
	ACTUAL calls that did happen (in call order):
		<none>
```

### PR DESCRIPTION
**Pull request by cuitoldfish**

### CODE REVIEW

**Comment by cuitoldfish** [comment]
I would say I like this option most.
In the current design, `mockNamedValue` is the class to describe the "value", and it's close for changing the class content, the relation among members, and the relation between `mockNamedValue` and it's member,  but open for the modification for the value members, the value can have it's own discretion on type(void*, int, and so on) and off course behavior, member variable.
mock support is just one instance of that "value", and it deserve it's own scope_ member to make itself more definitely.
what's more, the duplication here is not so bad because scope in `mockNamedValue` and `mockSupport` both from the same sources then no possibility to have the non-uniformity between the two scope.

**Comment by basvodde** [comment]
Shouldn't you set the scope in getMockSupportScope, when the scope gets created?

**Comment by cuitoldfish** [comment]
I currently do set scope  in getMockSupportScope, just after clone()

**Comment by basvodde** [comment]
Ah yes, I missed that. Only thing, could you rename the withScope to just setScope or so ? I believe the withScope/setScope isn't going to be used by CppUTest users themselves, correct? Now it suggests it is similar to the other with methods, whereas it probably isn't.

**Comment by cuitoldfish** [comment]
I agree, this function should be confined to be used inside the mockSupport class.

how about change the name to `completeMockSupportWithScope`?  and shall we declare this small function to inline?

**Comment by basvodde** [comment]
How about adding the scope to clone ?

**Comment by cuitoldfish** [comment]
I was thinking this yesterday, and also declare the scope_ to const, but I have concern to change the meaning of clone() because we need to pass the scope name to clone() function

**Comment by basvodde** [comment]
Clone is only used there, right?

**Comment by cuitoldfish** [comment]
yeah, I mean the `clone` has one world known meaning, extra parameter will change that and then add misunderstanding to the readebility

**Comment by basvodde** [comment]
I think it is ok, especially if you consider scope to be kinda equal to the name of the Mock. So, lets just change clone and have a default parameter to "".

**Comment by cuitoldfish** [comment]
OK. and I prefer to rename scope_ to mockName_, and make it const which can only be set when mockSupport is constructed, no possibility to get changed

**Comment by basvodde** [comment]
Thanks

**Pull request merged**
