### PR TITLE
One more file pulled out

### PR DESCRIPTION
**Pull request by basvodde**
And one more!

### CODE REVIEW

**Comment by arstrube** [comment]
Needs changing the VS projects still, doesn't it? They won't fail, because they don't know about the additional file.

**Comment by basvodde** [comment]
Yes, but lets first finish them, there is one or two more to go.

**Comment by arstrube** [comment]
Okay

**Comment by arstrube** [comment]
Are you going to merge this one, or extract the others first?

**Comment by basvodde** [comment]
Patience :)

**Pull request merged**
