### PR TITLE
Refactored CommandLineRunner to allow for new TestOutput

### PR DESCRIPTION
**Pull request by basvodde**
Small refactoring to allow for pulling out the ConsoleOutput further.

### CODE REVIEW

**Comment by arstrube** [comment]
That's a minimal step for sure. Looks good to me.

I did an actual refactoring of TestOutput (no PR yet). I'm not entirely happy with it. It also tends to affect a lot more files (that's in the nature of things). I will combine yours with that tongight; the should complement each other well.

I'm haveing problems with StringButterTestOutput vs. ConsoleTestOutput, needing at least one cast. No casts were necessary before, so I don't like that.

**Comment by arstrube** [comment]
P.S. I guess it wasn't so much for me to comment, but it looks good anyway :)

**Comment by basvodde** [comment]
Simplified the CommandLineRunner further. Now it doesn't have the complication it had before and less parameters

**Comment by arstrube** [comment]
Hmm. What are the advantages over my PR #596? Does this already print -v and -junit concurrently, or is just a preparatory step?

**Comment by arstrube** [comment]
@basvodde okay, I merged this with my PR #596 and it merges with no problems and works as expected. Although this is kind of optional ;-). I also discovered an oversight in that failures weren't printed, which I corrected.

**Pull request merged**
