### PR TITLE
Appveyor multiplatform

### PR DESCRIPTION
**Pull request by Andne**
I've added support to appveyor so that it runs MinGW as both a 32-bit and 64-bit build.

### CODE REVIEW

**Comment by arstrube** [comment]
Great. Could you perhaps in the lack of failure output? It registers the failure, but does not seem to ouptput the failure string.

**Comment by arstrube** [comment]
As can be seen here: https://ci.appveyor.com/project/arstrube/cpputest/build/3.7.0-ci8/job/msyphrqx8oeo9kpl

**Comment by Andne** [comment]
If you go to the tests tab, it shows you the full error message there.  Do you want the output in the console too?  That is possible I'm sure, I just liked having the test information stay on it's own page.  However, I should probably make the message page show the details as well.

**Comment by arstrube** [comment]
Oh, kewl. No, I didn't know that. In that case, that's much more convenient than console output.

If you still consider it a good idea, maybe we could run the tests with -v -junit. But, as for me, that's not necessary. I just didn't know my way around AppVeyor well enough.

**Pull request merged**
