### PR TITLE
Quieter autoconf

### PR DESCRIPTION
**Pull request by charlesnicholson**
enable [subdir-objects] in AM_INIT_AUTOMAKE, fix bug in Makefile.am. Subdirectory artifacts like Platforms/Gcc/... now get correct output directories.

### CODE REVIEW

**Comment by charlesnicholson** [comment]
hmm, looks like everything in autotools-land is working but getting interesting errors over from AppVeyor:

https://ci.appveyor.com/project/basvodde/cpputest/build/3.7.0-ci445/job/3ak46mb6g9ieoex8

Bottom of the log is this:

[00:02:42] 
[00:02:42] cmake -G 'MinGW Makefiles' ..
[00:02:42] 
[00:02:43] cmake : CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.4/Modules/CMakeMinGWFindMake.cmake:22 (message):
[00:02:43] At line:1 char:1
[00:02:43] + cmake -G 'MinGW Makefiles' ..;$err = $?
[00:02:43] + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[00:02:43]     + CategoryInfo          : NotSpecified: (CMake Error at ...e:22 (message)::String) [], RemoteException
[00:02:43]     + FullyQualifiedErrorId : NativeCommandError
[00:02:43]  
[00:02:43]   sh.exe was found in your PATH, here:
[00:02:43] 
[00:02:43]   C:/Program Files/Git/usr/bin/sh.exe
[00:02:43] 
[00:02:43]   For MinGW make to work correctly sh.exe must NOT be in your path.
[00:02:43] 
[00:02:43]   Run cmake from a shell that does not have sh.exe in your PATH.
[00:02:43] 
[00:02:43]   If you want to use a UNIX shell, then use MSYS Makefiles.
[00:02:43] 
[00:02:43] Call Stack (most recent call first):
[00:02:43]   CMakeLists.txt:1 (project)
[00:02:43] 
[00:02:43] 
[00:02:43] 
[00:02:43] 
[00:02:43] CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
[00:02:43] 
[00:02:43] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
[00:02:43] 
[00:02:43] -- Configuring incomplete, errors occurred!
[00:02:43] Command Returned error: 1
[00:02:43] 
[00:02:43] Command executed with exception: 
[00:02:43] CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage

Any ideas?

**Comment by charlesnicholson** [comment]
@basvodde I'm pretty sure this fixes the automake / autoconf noise, if you're interested.

**Comment by charlesnicholson** [comment]
All checks green now that Appveyor is healthy again.

**Comment by charlesnicholson** [comment]
Any thoughts on this? @basvodde you mentioned that it was a bug in autoconf, but after fixing the latent AC_SUBST bug in Makefile.am, it seems to run cleanly with subdir-objects enabled.

**Comment by basvodde** [comment]
Yes, excellent! Thanks!

Maybe the bug was in my head. But I noticed you made one additional change, perhaps that was the problem I had earlier when I tried it. Anyways, it works in travis (linux) and I tried Mac and worked also. So, I guess it is ok :)

Sorry, I forgot to merge it after I had tested it on Mac. I thought I did. Thanks for reminding me.

**Comment by charlesnicholson** [comment]
Thanks, glad it helped. Sorry to pester. :)

**Pull request merged**
