### PR TITLE
Add header that defines std::nullptr_t.

### PR DESCRIPTION
**Pull request by dandwyer**
My GHS 7.1.4 compiler requires cstddef to get std::nullptr_t. This is somewhat expected given:
https://en.cppreference.com/w/cpp/types/nullptr_t
It may be better to put the cstddef include in StandardCLibrary.h, but I wanted to localize the change for context.

### CODE REVIEW

**Comment by basvodde** [comment]
Thanks. Instead, the std::null_ptr ought to be removed from CppUTest.

**Comment by dandwyer** [comment]
Are you saying you want the following function removed entirely from the header and source?:
SimpleString StringFrom(const std::nullptr_t value)

**Comment by basvodde** [comment]
If possible, yes. Need to check why it was there, but usually we do not want things like nullptr_t in the code because CppUTest ought to work with not fully latest standard compilers.

Either it got in because I didn't notice it, or it needs to be there in a way that can work when compilers don't fully support this.

**Comment by dandwyer** [comment]
Thank you for your quick replies to this pull request. I am concerned I may do more damage than good if I try to resolve your higher level concerns. In this case, my compiler has no issue with the use of std::nullptr_t, but it does need the header that provides the definition. Is this pull request viable as a quick fix on the way to a larger scope change?

**Comment by dandwyer** [comment]
Just found a datapoint that someone else has added cstddef as a pre-include to their build to work around this issue:
https://github.com/cpputest/cpputest/issues/1193

**Comment by basvodde** [comment]
Since it is the only place we use null_ptr, I cannot merge this pull request as it will take it away from where it needs to go.

Removing the null_ptr shouldn't be a large change.

**Comment by basvodde** [comment]
I spend a bit more time looking at this. It looks like the nullptr_t is around the appropriate #ifdef already and outside the class, so that can stay.

I cannot accept this pull request though as including a C++ library header outside the CStandardLibrary.h is not ok. When I looking in the StandardLibrary.h, it already has a #include <stddef.h>  in there, which ought to be equal to the include you are trying to add.

Would you mind checking why that one isn't enough?

Thanks!

**Comment by basvodde** [comment]
Yeah, this will do. Thanks!

**Comment by dandwyer** [comment]
@basvodde , Thanks for your help on these pull requests. I am happily building off of master now!
-Dan

**Pull request merged**
