### PR TITLE
[Reopen] change getOneFulfilledExpectationWithIgnoredParameters to right name

### PR DESCRIPTION
**Pull request by cuitoldfish**
This PR seems closed exceptionally by me, now reopen it

### CODE REVIEW

**Comment by cuitoldfish** [comment]
again, not know what happened with the AppVeyor.
>Build started
git clone -q https://github.com/cpputest/cpputest.git C:\projects\cpputest
git fetch -q origin +refs/pull/978/merge:
git checkout -qf FETCH_HEAD
Running Install scripts
if ($env:Platform -like 'MinGW*') { choco install mingw --version $env:PlatformToolset $( if ($env:Platform -like '*32') { Write-Output -forcex86 } ) | Out-Null }
Command exited with code 1


@arstrube  do you know why?

**Comment by arstrube** [comment]
No, I don't know why. Happened to me, too. It's an install problem; guess we just have to ignore it for now

**Comment by arstrube** [comment]
It seems to be working again. If you close and reopen the PR, you should get a clean bill of healt ;-)

**Comment by basvodde** [comment]
Not relevant anymore as all been renamed in the mean time.

**Pull request closed without merging**
