### PR TITLE
First Stab At Building and Running real CPPU1.EXE

### PR DESCRIPTION
**Pull request by arstrube**
Built the first test executable.

### CODE REVIEW

**Comment by arstrube** [comment]
Rebased on #761.

**Comment by basvodde** [comment]
This one needs a rebase too ?

**Comment by arstrube** [comment]
Very much so. Many conflicts. Hopefully got it all right.

**Comment by basvodde** [comment]
The diff looks fine

**Comment by arstrube** [comment]
I noticed the log is more verbose now (it echoes commands), which is often desirable, but there are a few places where I'd rather not have it (e.g. printf 'bla' is irritating when repeated).

I suppose I use '@' ? Did you change this on purpose, or did it happen accidentally?

**Comment by basvodde** [comment]
Yeah, it is the x in set -ex. I thought a bit more verbosity would help us.

**Pull request merged**
