### PR TITLE
Composite Test Output

### PR DESCRIPTION
**Pull request by basvodde**
Merged the Composite in the existing header and source. Also added some functionality.

### CODE REVIEW

**Comment by arstrube** [comment]
1. Looking good.
2. Might default outputs work here (see my PR #596 )? It made a lot of sense there, but I'm not sure yet how you plan to hook it up with CommandLineTestRunner.

**Comment by basvodde** [comment]
It was actually 4 additional lines in CommandLineTestRunner. I'll put them in a pull request tomorrow.

**Comment by arstrube** [comment]
There is a strange test failure I noticed working on something else in VC6:
```bash
D:\DEV\05_CPPUTEST\CPPUTEST\tests\TestOutputTest.cpp(381): error: Failure in TEST(CompositeTestOutput, PrintTestFailure)
 expected <
file:10: error: Failure in TEST(Group, Name)
 failed
>
 but was  <
file(10): error: Failure in TEST(Group, Name)
 failed
>
 difference starts at position 5 at: <     
file(10): erro>
                                           
```

**Comment by arstrube** [comment]
Ah, I see. This bug is a feature ;-)

Looks like you need to:
1) set the working environment to eclipse in setup()
2) do an additional test with the working environment explicitly set to vistualStudio

**Comment by basvodde** [comment]
Only 1) and only in one test. Let me do that later.

**Comment by arstrube** [comment]
....well not that I disagree but that's how the existing tests are done :-)

**Pull request merged**
