### PR TITLE
MSVC2015 64-bit compile fix for pointers, see #783

### PR DESCRIPTION
**Pull request by andrew-elder**

### CODE REVIEW

**Comment by andrew-elder** [comment]
Now I see this fix may be addressed here https://github.com/cpputest/cpputest/pull/847 ?

**Comment by andrew-elder** [comment]
Is travis build broken? What happened to it?

**Comment by basvodde** [comment]
Yup, the fix doesn't compile on clang....

**Comment by andrew-elder** [comment]
Is there a better approach to fix the MSVC2015 64-bit compile?

**Comment by Andne** [comment]
I have a solution for the SimpleStringTest.cpp warning, but it requires that I assume that `CPPUTEST_USE_LONG_LONG` will always be enabled on 64-bit platforms with 32-bit longs (Windows mainly I think).

@basvodde Are you ok with me making this assumption?  Seems like it ought to be valid since if you have 64-bit pointers and 32-bit longs you need some way to create a 64-bit integer.  This also fixes a test that has two forms currently.

Another solution I'm finding is to avoid any possibility of sign-extension occurring by making sure the most significant bit is 0.  Changing the constants to be less than 0x80000000 seems to work pretty well.

**Comment by andrew-elder** [comment]
Thanks for adding to this discussion @Andne. It did seem that making sure CPPUTEST_USE_LONG_LONG is defined would be another solution to the problem.

**Comment by basvodde** [comment]
@Andne At this moment, I can't think of a reason why we can't assume it.

**Comment by andrew-elder** [comment]
Closing this pull request because the same problem is solved more cleanly in https://github.com/cpputest/cpputest/pull/1124.

**Pull request closed without merging**
