### PR TITLE
Terrible hack without typedef. No type safety of any kind.

### PR DESCRIPTION
**Pull request by arstrube**
Use at your own risk.

### CODE REVIEW

**Comment by basvodde** [comment]
Closed and deleted? That is something :)

**Comment by arstrube** [comment]
Wasn't meant to be a pr against cpputest/cpputest in the first place ;-). Just meant to be here.....

**Comment by arstrube** [comment]
How do you like it :-P? No more typedef, hehe.

**Comment by arstrube** [comment]
The one to look at is here: https://github.com/arstrube/cpputest/pull/4

**Pull request closed without merging**
