### PR TITLE
Added osX to travis

### PR DESCRIPTION
**Pull request by basvodde**
Does the Travis osx work?

### CODE REVIEW

**Comment by arstrube** [comment]
Umm, not really. Should it?

**Comment by arstrube** [comment]
"Manual intervention required

This feature needs to be enabled manually. If you wish to take advantage of this feature, please send email to support@travis-ci.com, indicating which repository you would like to have it enabled."

**Comment by arstrube** [comment]
Maybe do this, too, initially:
```
matrix:
  allow_failures:
    - os: osx
```
so builds don't fail just because the osx build isn't quite right yet.

**Comment by basvodde** [comment]
Yeah, but they also said they don't have capacity for more osX projects, so I wanted to try out to see what happens. Now I know, nothing happens :)

**Comment by arstrube** [comment]
hehe :-)

**Comment by arstrube** [comment]
@basvodde - I see you merged it. In that case, wouldn't it be better to add the allow-failures bit above as well? We don't want all builds to break the day they enable it, no?

**Comment by basvodde** [comment]
I closed it, not merged it :)

**Comment by arstrube** [comment]
oh. my bad.

**Pull request closed without merging**
