### PR TITLE
Changed version to 4.0

### PR DESCRIPTION
**Pull request by basvodde**

### CODE REVIEW

**Comment by offa** [comment]
@basvodde There's a release of 4.0, but these changes are missing.

**Comment by basvodde** [comment]
HAHAAHAHAHAHAHHA

**Comment by basvodde** [comment]
I think that is the ultimate stupidity :)

**Comment by basvodde** [comment]
Ok, I think I fixed it.

**Comment by offa** [comment]
Well then, congratulations for v4.0 :smile:  :tada: .

**Comment by r4nd0m6uy** [comment]
Woohoo I was eager to open the champain! Thanks for the great work!

**Comment by basvodde** [comment]
Can you send over some of that champagne? :)

**Comment by r4nd0m6uy** [comment]
Here you go -> :champagne:

:rofl:

Honestly, I wish I could .. :disappointed:

**Pull request merged**
