### PR TITLE
Fix for issue  #831

### PR DESCRIPTION
**Pull request by arstrube**
This fixes issue #831.

### CODE REVIEW

**Comment by basvodde** [comment]
Ok. Good. Whats the formatting things though?

**Comment by arstrube** [comment]
Spaces?!

**Comment by arstrube** [comment]
Separate PR / commit preferred, right?

**Comment by basvodde** [comment]
Well, its merged already. Some changes seemed formatting, which made it not too easy to read.

**Comment by arstrube** [comment]
Oh. Sorry about that. The teeny-weeny spaces seemed okay to me, at least looking at them on these Github pages.

**Comment by arstrube** [comment]
they do make for a lot of noise in the commandline diff....

**Comment by arstrube** [comment]
...my sincere apologies. It wasn't a good idea to mix them in with the fix.

**Pull request merged**
