### PR TITLE
Dosbox has been white-listed

### PR DESCRIPTION
**Pull request by arstrube**
With this PR, we'd be using the new, container-based infrastructure on Travis CI.

Is that cool, or is that cool?

### CODE REVIEW

**Comment by arstrube** [comment]
There is one remaining sudo in the Dos job. It is needed in order to get execute permissions on the watcom/binl directory. Is there perhaps another way to get execute permissions on the Watcom binaries?

**Comment by arstrube** [comment]
Part of the problem with Watcom C is that it's Linux executables (wcc etc.) don't have the x permission set to start with. So one needs to use sudo chmod.

**Comment by arstrube** [comment]
@basvodde - https://travis-ci.org/cpputest/cpputest/builds/107014698. Looks good, no?

**Comment by basvodde** [comment]
That is indeed good!

**Pull request merged**
