### PR TITLE
Test for -p option

### PR DESCRIPTION
**Pull request by arstrube**
This should fail.

### CODE REVIEW

**Comment by basvodde** [comment]
I think it did fail before :)

**Comment by arstrube** [comment]
Is it okay then to test without CppUTestExt for now?

**Comment by basvodde** [comment]
Yeah, I guess so :(

**Comment by arstrube** [comment]
Any other reason why this pull request should not be merged?

**Comment by basvodde** [comment]
Other than that I didn't know it was ready... uhm... no :)

**Pull request merged**
