### PR TITLE
Overlooked this one in my npos-2 PR

### PR DESCRIPTION
**Pull request by arstrube**

### CODE REVIEW

**Comment by basvodde** [comment]
Anything we can do with the randomly failing mingw? Can we put a retry in the build file?

**Comment by arstrube** [comment]
I don't know. You can restart Appveyor. I close and reopen the PR to force it to restart until it passes. Not elegant :P

**Comment by basvodde** [comment]
No, but it always fails at the same time, so we ought to be able to put that in a loop and try multiple times?

**Comment by arstrube** [comment]
I guess so...

**Pull request merged**
