### PR TITLE
Creating a Borland/UtestPlatform.cpp

### PR DESCRIPTION
**Pull request by pjshelton**
I am using as the base for the Borland/UtestPlatform.cpp file the Gcc/UtestPlatform.cpp file.  This is currently just a copy of the Gcc/UtestPlatform.cpp file.

I will make changes to it in later PR.  This way it will be easier for you to see what I do change, rather than just dump the final updated file on you with unknown changes and no reasoning as to why the differences.

This is in response to the first reply in #1493.

### CODE REVIEW

**Comment by basvodde** [comment]
So, I will not merge this? Now it still even has Gcc all over it, so slightly uncomfortable merging it :)

**Comment by pjshelton** [comment]
Okay, I can remove what I think I don't need.  unfortunately this is going to be a case of you are going to have trust that what is left works because at the moment you don't have the borland  compiler to do your own testing with.  it becomes a "large" change.
I made this work by taking what you had done and make just enough changes to get it working. So there is going to be a large number of things that strictly don't need to be there but are because I don't strictly need to remove them because the compiler does.

**Comment by basvodde** [comment]
Ok, that is ok too. So, I'll merge this now?

**Comment by pjshelton** [comment]
Yes please.  The change that will let this file be used in a compilation will come later.

**Pull request merged**
