### PR TITLE
Repair CMake install

### LINKED ISSUE #1570: CMake installation is broken
After installing with CMake, `find_package(CppUTest REQUIRED)` succeeds, but the `CppUTest::CppUTest` and `CppUTest::CppUTestExt` targets are not defined.

### PR DESCRIPTION
**Pull request by thetic**
Closes #1570

### CODE REVIEW

**Review by offa — APPROVED** [review]

**Comment by thetic** [comment]
@jgonzalezdr Do you mind giving this a look when you have a chance? I think I've retained the behavior you added in #1538, but I'd like confirmation since I'm not sure I fully understand the use case.

**Comment by basvodde** [comment]
Closed because done in other PRs ?

**Comment by thetic** [comment]
I'm gonna get this under test in CI before I reopen this.

**Comment by thetic** [comment]
#1624

**Pull request closed without merging**
