### PR TITLE
Proposal: Remove options to disable std C library

### LINKED ISSUE #1656: Use without C stdlib is untested
```
#0  0x0000000000000000 in ?? ()
#1  0x0000555555721e41 in checkedMalloc (size=5) at src/CppUTest/TestMemoryAllocator.cpp:35
#2  0x000055555572239a in TestMemoryAllocator::alloc_memory (this=0x55555582e5a0 <defaultNewArrayAllocator()::allocator>, size=5) at src/CppUTest/TestMemoryAllocator.cpp:164
#3  0x000055555571db1b in SimpleString::allocStringBuffer (_size=5, file=0x555555764028 "src/CppUTest/SimpleString.cpp", line=629)
    at src/CppUTest/SimpleString.cpp:122
#4  0x000055555571f3c7 in SimpleString::copyToNewBuffer (bufferToCopy=0x555555765468 "null", bufferSize=5) at src/CppUTest/SimpleString.cpp:629
#5  0x000055555571e011 in SimpleString::copyBufferToNewInternalBuffer (this=0x55555582e890 <NullTestPlugin::instance()::_instance+16>, otherBuffer=0x555555765468 "null", bufferSize=5)
    at src/CppUTest/SimpleString.cpp:257
#6  0x000055555571e11f in SimpleString::copyBufferToNewInternalBuffer (this=0x55555582e890 <NullTestPlugin::instance()::_instance+16>, otherBuffer=0x555555765468 "null")
    at src/CppUTest/SimpleString.cpp:284
#7  0x000055555571e183 in SimpleString::SimpleString (this=0x55555582e890 <NullTestPlugin::instance()::_instance+16>, otherBuffer=0x555555765468 "null") at src/CppUTest/SimpleString.cpp:298
#8  0x000055555572e200 in TestPlugin::TestPlugin (this=0x55555582e880 <NullTestPlugin::instance()::_instance>, next=0x0) at src/CppUTest/TestPlugin.cpp:37
#9  0x000055555572e6d9 in NullTestPlugin::NullTestPlugin (this=0x55555582e880 <NullTestPlugin::instance()::_instance>) at src/CppUTest/TestPlugin.cpp:153
#10 0x000055555572e72e in NullTestPlugin::instance () at src/CppUTest/TestPlugin.cpp:159
#11 0x000055555571b48d in TestRegistry::TestRegistry (this=0x55555582e4e0 <TestRegistry::getCurrentRegistry()::registry>) at src/CppUTest/TestRegistry.cpp:33
#12 0x000055555571c0ba in TestRegistry::getCurrentRegistry () at src/CppUTest/TestRegistry.cpp:160
#13 0x0000555555733425 in TestInstaller::TestInstaller (this=0x555555820268 <TEST_SetPointerPluginTest_installTwoFunctionPointer_Installer>, shell=..., groupName=0x555555734242 "SetPointerPluginTest",
    testName=0x555555734228 "installTwoFunctionPointer", fileName=0x555555734080 "tests/CppUTest/SetPluginTest.cpp", lineNumber=77) at src/CppUTest/Utest.cpp:969
#14 0x00005555556658f5 in __static_initialization_and_destruction_0 (__initialize_p=1, __priority=65535) at tests/CppUTest/SetPluginTest.cpp:77
```

I suspect this was broken somewhere around #1364, which invariably requires dynamic memory allocation.

### PR DESCRIPTION
**Pull request by thetic**
As best I can tell, this functionality has rotted. I don't think it is feasible or responsible to attempt to maintain functionality that is not under test. I think repair/test would require some significant redesign. As such I propose to remove it outright.

Closes #1656.

### CODE REVIEW

**Comment by basvodde** [comment]
I don't really want to remove the feature as it is used when using CppUTest in e.g. Linux kernel development. That is when we added it.

**Comment by thetic** [comment]
Is there a version known to work or are there special instructions for testing it? I'd like to get it in CI if we want to keep it.

**Comment by basvodde** [comment]
The main thing is to keep the compiling in the CI. When that is in there then it isn't possible to include StdC headers directly without failing the build. So keeping that build then prevents regression. Then when people want to use CppUTest on kernel development or embedded development that has no stdC then they just need to implement the PlatformSpecific functions.

I have been thinking to try to implement some of the PlatformSpecific functions in an as much platform independent way (such as having a printf implementation) but haven't ever gotten to it and not sure it will actually be worth it.

**Comment by thetic** [comment]
I understand how to test that it builds, but how do we test that it _works_?

**Comment by thetic** [comment]
Let's continue discussion on https://github.com/cpputest/cpputest/issues/1656

**Pull request closed without merging**
