### PR TITLE
C++17 ci builds with latest gcc and clang

### PR DESCRIPTION
**Pull request by offa**
Builds the two C++17 linux builds with latest gcc and clang versions, providing feedback for the most recent compiler / standard versions.

### CODE REVIEW

**Comment by offa** [comment]
Travis failed due to some dos issue (not related to this PR).

**Comment by basvodde** [comment]
I'd prefer to have a different target for that, not the default one.

**Comment by basvodde** [comment]
And, is there any way to extract the latest compiler from the default? That would be nice.

**Comment by offa** [comment]
> I'd prefer to have a different target for that, not the default one.

You mean build? No problem, I'll update the PR accordingly.

> And, is there any way to extract the latest compiler from the default? That would be nice.

I don't think so. The default compiler is selected by ubuntu and typically not updated within a distribution version. Except the default, all compilers need to be installed with a version, eg. gcc-8 or clang-9.

**Comment by basvodde** [comment]
Included this in the travis build. But did manually as the file had changed so much.

**Pull request closed without merging**
