### PR TITLE
Test JUnitOutput properly again

### PR DESCRIPTION
**Pull request by arstrube**
Due to CommandLineTestRunnerWithStringBufferOutput overriding some methods for testing, the original methods weren't tested anymore.

This test tests the original methods.

### CODE REVIEW

**Comment by basvodde** [comment]
I'll merge it, but myself think these tests are not really needed.

**Comment by arstrube** [comment]
Thanks :).

If it is not really needed to test this function (because it is kind of wrapper-like and contains only one condtional expression...:P), then where does "not needed" actually stop? E.g.:

```c++
TestOutput* CommandLineTestRunner::createJUnitOutput(const SimpleString& packageName)
{
     JUnitTestOutput* junitOutput = new JUnitTestOutput;
     if (junitOutput != NULL) {
         junitOutput->setPackageName(packageName);
     }
     return junitOutput;
}
```
As opposed to createConsoleOutput(), which is tested indirectly 6 times, this code would no longer be tested at all.

**Comment by basvodde** [comment]
Sure, but I bet you can test the createJUnitOutput separately. I didn't, as it was extracted code and decided not to bother.

**Comment by arstrube** [comment]
Could you explain what you mean by testing createJUnitOutput "separately"? I am actually very curious.

BTW it does get exercised in at least one test run in the TravisCI, but coverage is not recorded in that run. Besides, that would by more of a system test, I guess.

**Comment by basvodde** [comment]
I mean, you call the method and figure out it created "the right object". Because when testing that, it doesn't mean you have to re-test the JUnitOutput class. That causes a piece of code to be tested via many tests, and that has a risk of high maintainability cost.

**Comment by arstrube** [comment]
Sounds good - lemme try whether I can figure out a way to do that.

About the other test -- I would be happy to take out the division-by-zero test and all of its prerequisites entirely, as it doesn't contribute  anything unique to testing CppUTest and rather seems to lead to some sort of odd compiler test :P  . What do you think?

**Comment by basvodde** [comment]
Its merged already. As long as it ain't causing harm, I don't mind integrating tests like these.

**Comment by arstrube** [comment]
So if division-by-zero trips us up again, I'll solve the problem by re moving the test :)

**Pull request merged**
