### PR TITLE
Moved functions in the cpp file

### PR DESCRIPTION
**Pull request by basvodde**
Removed the #define for VC6

### CODE REVIEW

**Comment by arstrube** [comment]
Yeah... as I said, that will break the Dos build :-/

**Comment by basvodde** [comment]
Why?

**Comment by arstrube** [comment]
Let me hunt for a compiler option. I would like that best, because only one compiler is concerned anyway....

**Comment by basvodde** [comment]
Uhm, I'd prefer to move the inline functions to a cpp file.

**Comment by basvodde** [comment]
Usually inline is only because of my laziness :)

**Comment by arstrube** [comment]
But there's also that there are some platforms that are easy to forget and hard / impossible for us to test. 

Perhaps it would be a good idea to create an issue for everything that involves adding / removing / renaming files, and then do them all at once (like with the splitting of mock tests).

My bad not to have proposed a separate source to begin with.

**Comment by basvodde** [comment]
Yeah, perhaps...

**Pull request closed without merging**
