### PR TITLE
Included operator delete with size for new gcc

### PR DESCRIPTION
**Pull request by basvodde**
As title.

### CODE REVIEW

**Comment by arstrube** [comment]
nice.

**Comment by arstrube** [comment]
ummm... tests? Coverage decereased by a whopping 0.07 percent ^.^

**Comment by offa** [comment]
I have just tested on Gcc 6; all fine so far, the warning (#957) didn't show up.

**Comment by basvodde** [comment]
Added now. Wanted to check if it compiles at all on all our compilers. Lets see about the test as the syntax for calling it is somewhat unusual :)

**Pull request merged**
