### PR TITLE
Plugin to check for IEEE754 floating point exception flags automatically

### PR DESCRIPTION
**Pull request by arstrube**
I propose a plugins/ directory for contributed plugins.

It would be good to have Travis CI checks on this.

### CODE REVIEW

**Comment by arstrube** [comment]
Actually, it is also g++-only at this point. No idea how it works with VS or clang (yet).

**Comment by arstrube** [comment]
Moved the plugin to a more appropriate location.

__Like:__
+ It is separate from actual CppUTest, which reflects that only people who really want this will include it in their tests
+ It has its own Makefile

__Dislike:__
+ It is not included in the Travis CI build

What would be needed to run the tests is something like (libCppUTest.a is expected in the usual place):
```bash
pushd ../plugins/IEEE754ExceptionFlagsPlugin
make check clean
popd
```
I wouldn't want to give it a separate target in the build matrix, because there would be such a big overhead for such a tiny test.

There is no point in running the examples, because all tests in the examples are tests that will fail on purpose. This is why they are in a separate demo 'test'.

@basvodde - your thoughts?

**Comment by basvodde** [comment]
Why not just put it in CppUTestExt for now? Especially considering we'll be pulling out the CppUMock, it feels like the right place?

**Comment by arstrube** [comment]
Okay. That would be fine with me. Also, we could run tests on Travis CI and it would be a lot easier for those who want to install it (no separate Makefile and lib).

**Comment by arstrube** [comment]
If we do that, what do we do with the demo tests that fail (and are meant to fail, to demonstrate that no explicit check is necessary to pick up problems)?

There is at least one build that runs the examples/ tests and would fail if they do.

**Comment by arstrube** [comment]
Oh. An even more important issue. The plugin has to be compiled with C++11, because this feature is only available in C++11. It can still pick up faults in C code compiled with other standards, but as far as I recall, CppUTest must compile without C++11 enabled. So actually, we cannt put it into extensions, right?

Unless we compile it conditionally.

**Comment by arstrube** [comment]
So, I would imagene the intire plugin and its tests and demo must be within an `#ifdef` for C++``, and that should settle it, because to my knowledge the examples are not tested with C++11.

It has to be said though that once it has been compiled, C++11 is not a prerequisite.

**Comment by basvodde** [comment]
Can't you change the demo test in a positive test :)

And yeah, I guess it needs to be in a #ifdef C++11 block, which is fine.

**Comment by arstrube** [comment]
@basvodde how to proceed? The plugin requires C++11 to compile. Which is why I think it would not be a good idea to put it with CppU Extensions after all. Currently, I compile it separately with its own Makefile, and then simply link the library.

It has really proven itself useful working with floating point math, pinpointing potential problems.

To put it in extensions, we would need some mechanism to dis-/enable C++11 for individual sources. I don't know whether that is possible, or desirable.

**Comment by Andne** [comment]
Do the demo/example tests need to be run?  Compiling them makes sense to make sure nothing related to the API changed, but what is gained by running them.  Another option would maybe be to wrap them running such that you want a return value greater than or equal to 0.  That would at least ensure that there wasn't a crash in the examples I think, assuming those cause a negative return value.

**Comment by arstrube** [comment]
Hi Andy, the demo / example tests are not run by default. In order to build and run them, one needs to issue the command
```
make demo
```
I wouldn't run them as part of the build process; they are meant for the user to see how things work and perhaps experiment with it.

**Comment by arstrube** [comment]
Oops. didn't mean to close...

The actual tests use a fixture, so they will never return a failure.  I am busy adding wrappers for feenableexcept() and fedisableexcept(). In order to test that, I might add tests that run in a separate process on those systems that support such things. Not sure yet.

**Comment by Andne** [comment]
Ok, I misunderstood then, I thought you were saying that one build does run the demo tests which would be a problem with this plugin since you make the test fail in order to illustrate how it works.

**Comment by basvodde** [comment]
Why not just put it under #if ?

**Comment by arstrube** [comment]
@basvodde - something like "#if c++11 is configured", right? All plugin code and all tests would be wrapped by one #if?

I ran into nasty problems on MacOS.
1. It doesn't have `feenableexcept()` `fedisableexcept()`. There is public domain substitute code to take care of that. Another #if / #else....
2. On my Mac, I can't get the flags to work at all. If I use the public domain feenableexcept(), then it duly crashes. if not, nothing seems to happen. I found that you're supposed to use `#pragma STDC FENV_ACCESS ON`, however, with that, nothing happens either.

**Pull request closed without merging**
