### PR TITLE
Restore DOS build in CI

### PR DESCRIPTION
**Pull request by thetic**

### CODE REVIEW

**Comment by offa** [comment]
The DOS build fails on *master*: https://github.com/cpputest/cpputest/runs/7898131248?check_suite_focus=true

```
/home/runner/work/cpputest/cpputest/tests/CppUTest/TestFailureNaNTest.cpp(122): Warning! W014: col(0) no reference to symbol 'failFileName'
/home/runner/work/cpputest/cpputest/tests/CppUTest/TestFailureNaNTest.cpp(35): Note! N392: col(13) definition: 'char const * <unique>::failFileName'
```

Since the PR build was successful, it might be caused by some recent changes.

**Comment by basvodde** [comment]
The "fix the DOS build" PR was done after this PR. So, I assume this PR was successful because there was no DOS build yet on that PR.

**Comment by basvodde** [comment]
Sorry, the other PR I'm referring to is the one about INF checking in CMake files. I think that is the cause of the failure (as I merged them gradually)

**Comment by thetic** [comment]
https://github.com/cpputest/cpputest/pull/1618

**Pull request merged**
