### PR TITLE
Work around Apple Clang's quirks

### PR DESCRIPTION
**Pull request by thetic**
Depends on:

- #1601 by @offa.
- #1605 by me.

Resolves warnings from #1604.

### CODE REVIEW

**Comment by thetic** [comment]
I don't have access to apple clang outside of github actions. Best I can tell, some versions of apple clang support `override` as an extension to C++98.

**Comment by mtfurlan** [comment]
I refuse to use a mac so I'm testing with https://github.com/sickcodes/Docker-OSX/
It's matched my coworkers actual hardware with everything so far, but I can make a coworker run this tomorrow.

**Comment by mtfurlan** [comment]
Coworker gets the same `'override' keyword is a C++11 extension` warnings building your branch.

**Comment by thetic** [comment]
are you providing your own flags are are these all defaults? It's rather odd to build with `-Weverything`, especially without setting a language standard.

**Comment by mtfurlan** [comment]
Building your cpputest branch with `./autogen.sh && ./configure && make -j8`, that warning shows up as a warning.

When using MakefileWorker.mk with clang, `-Weverything` is set here: https://github.com/cpputest/cpputest/blob/master/build/MakefileWorker.mk#L209=
It was added in https://github.com/cpputest/cpputest/commit/7ce5f6428a3a05c590aa0531a742de208a198086

**Pull request closed without merging**
