### PR TITLE
Readme updated

### PR DESCRIPTION
**Pull request by offa**
Some updates for the readme.

### CODE REVIEW

**Comment by basvodde** [comment]
Then you could make it even simpler by using the default main macro that is provided by CppUTest :)

**Comment by offa** [comment]
@basvodde I didn't know, there's a default main macro. This should be added to the documentation too.

**Comment by arstrube** [comment]
@offa he sneaked it in recently without anybody noticing :-)

**Comment by offa** [comment]
That's true!

**Comment by basvodde** [comment]
Uhm, well, I didn't consider it a major feature. Just a convenience ;)

**Pull request merged**
